name: stacked_localisation_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build:
  source_gen:
  analyzer:
  mustache: ^1.1.1

dev_dependencies:
  test:
  build_runner:
